language: node_js
if: tag IS blank

osx_image: xcode10.2

dist: trusty
sudo: false

node_js:
  - "node"

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test; fi
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      git config --local user.name "Juan Cruz Martinez"
      git config --local user.email "bajcmartinez@gmail.com"
      git tag "$(node -p 'require(`./package.json`).version')";
    fi;

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    draft: true
    skip_cleanup: true
    file_glob: true
    file: "dist/Google Tasks UI*"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: googletasksui.com
    local_dir: build
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
