language: node_js
if: tag IS blank

node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run react-build

before_deploy:
  - npm run release
  - git config --local user.name "Juan Cruz Martinez"
  - git config --local user.email "bajcmartinez@gmail.com"
  - git tag "$(node -p 'require(`./package.json`).version')";

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - "dist/Google Tasks UI*"
    on:
      branch: master