language: node_js
if: tag IS blank

node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run react-build

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      npm run release
      git config --local user.name "Juan Cruz Martinez"
      git config --local user.email "bajcmartinez@gmail.com"
    fi;

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - "dist/Google Tasks UI*"
    on:
      branch: master
  - provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: googletasksui.com
      local_dir: build
      skip_cleanup: true
      on:
        branch: master

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
